config/routes.rb
Trial::Application.routes.draw do

root 'users#index'
 resources :users
 resources :sessions

 get 'users/new' => 'users#new'
 post 'users/new' => 'users#create'
 get 'sessions/login' => 'sessions#show'
 post 'sessions/login' => 'sessions#login_attempt'
 get 'sessions/logout' => 'users#index'
 
 

end

app/models/user.rb
class User < ActiveRecord::Base
 attr_accessor :password

validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
validates :password, :confirmation => true #password_confirmation attr
validates_length_of :password, :in => 6..20, :on => :create

	before_save :encrypt_password
	after_save :clear_password

	def encrypt_password
		if password.present?
			self.salt= BCrypt::Engine.generate_salt
			self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
		end
	end

	def clear_password
		self.password=nil
	end

	def self.authenticate(name="", login_password="")
		user = User.find_by_name(name)
		
		if user && user.match_password(login_password)
			return user
		else
			return false
		end
	end

	def match_password(login_password="")
		encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected
	def authenticate_user
		if session[:user_id]
			@current_user=User.find session[:user_id]
			return true
		else
			redirect_to(:controller => 'sessions', :action =>'show')
			return false
		end
	end

	def save_login_state
		if session[:user_id]
			redirect_to :root
			return false
		else
			return true
		end
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def show
end

def login_attempt
		authorized_user = User.authenticate(params[:name],params[:login_password])
			if authorized_user
				session[:user_id] = authorized_user.id
				flash[:notice] = "Wow Welcome again, you logged in as #{authorized_user.name}"
				render "home"
			else
				flash[:notice] = "Invalid Username or Password"
				flash[:color]= "invalid"
				redirect_to 'show'
			end
end


def logout
	session[:user_id] = nil
	redirect_to :action => 'show'
end

def home
	@current_user=User.all
end

before_filter :authenticate_user, :only => [:home]
before_filter :save_login_state, :only => [:login, :login_attempt]

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user=User.new
	end

	def index
	end

	def create
		@user=User.new(user_params)
		if @user.save
			flash[:now]= "Created!"
			redirect_to sessions_login_path
		else
			render 'new'
		end
	end

	before_filter :save_login_state, :only => [:new, :create]

	private
	def user_params
		params.require(:user).permit(:name, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>

  <title>Trial</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	
<%= yield %>

</body>
</html>

app/views/users/_logging.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
			<div class="navbar-header">
				<div class="container pull-left">
					<nav>
				<a class="navbar-brand pull-left" href="#">
					<span class="glyphicon glyphicon-heart"></span>
					    <li><%= link_to "Home", users_path %></li>
						<li><%= link_to "Sign In", sessions_login_path %></li>
						<li><%= link_to "Sign Up", users_new_path %></li>
				</a>
			        </nav>
				</div>
			</div>
</nav>

app/views/users/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<%= render "logging" %>
<div class="center hero-unit"><h1> Sign in or sign up to book tickets for your favourite movies!</h1></div>

app/views/users/new.html.erb
<div class="Sign_Form">
	<nav class="navbar navbar-default navbar-inverse" role="navigation">
			<div class="navbar-header">
				<div class="container pull-left">
					<nav>
				<a class="navbar-brand pull-left" href="#">
						<li><%= link_to "Home", users_path %></li>
						<li><%= link_to "Sign In", sessions_login_path %></li>
						
				</a>
			        </nav>
				</div>
			</div>
</nav>
<h1>Sign Up</h1>
<%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
<p> Username:</br> <%= f.text_field :name %> </p>
<p> Password:</br> <%= f.password_field :password%></p>
<p>Password Confirmation:</br> <%= f.password_field :password_confirmation %></p>
<%= f.submit :Signup %>

<% end %>
<% if @user.errors.any? %>
<ul class="Signup_Errors">
<% for message_error in @user.errors.full_messages %>
<li><%= message_error %></li>
<% end %>
</ul>
<% end %>
</div>